#!/bin/sh

# Додавање свих измењених датотека у git
git add .

make all

make clean

make > output.log 2>&1

# `C`` у `Markdown``
ruby ctomd.rb

# Покретање Prettier на свим датотекама
bun prettier --write .

# `C`` у `Markdown``
ruby ctomd.rb